name: "Integration"

on:
  pull_request:
    branches: ["main", "staging"]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync --lock
          uv pip install pre-commit
          pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files